services:
  postgres:
    image: postgres:18-alpine
    container_name: nodejs-capstone-project
    restart: unless-stopped

    ports:
      - "5444:5435"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodejs-capstone

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
